/*	$Id$	*/
/*
 * Copyright (c) 2025 C90 Backend Generator
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "pass1.h"

/*
 * C90 code generator - generates C code instead of assembly
 */

static int c90_header_emitted = 0;

/*
 * Emit C90 file header with necessary includes
 */
static void
emit_c90_header(void)
{
	if (c90_header_emitted)
		return;
	c90_header_emitted = 1;

	printf("/* Generated by PCC C90 backend */\n");
	printf("#include <stddef.h>\n");
	printf("\n");
}

/*
 * Print out segment name (translated to C constructs)
 */
void
setseg(int seg, char *name)
{
	emit_c90_header();

	switch (seg) {
	case PROG:
		/* Code segment - no special handling in C */
		printf("\n/* .text section */\n");
		break;
	case DATA:
	case LDATA:
		printf("\n/* .data section */\n");
		break;
	case UDATA:
		printf("\n/* .bss section */\n");
		break;
	case RDATA:
		printf("\n/* .rodata section */\n");
		break;
	case STRNG:
		printf("\n/* string constants */\n");
		break;
	default:
		if (name)
			printf("\n/* section: %s */\n", name);
		break;
	}
}

#ifdef MACHOABI
void
defalign(int al)
{
	/* Alignment is implicit in C90 */
}
#endif

/*
 * Define location for data/function
 */
void
defloc(struct symtab *sp)
{
	char *name = getexname(sp);

	if (sp->sclass == EXTDEF) {
		/* Will be defined later as actual C declaration */
	}
	/* Symbol definition handled in C declaration syntax */
}

/*
 * Code for the end of a function
 */
void
efcode(void)
{
	/* Function epilogue is handled by local2.c */
}

/*
 * Beginning of file
 */
void
bfcode(struct symtab **a, int n)
{
	emit_c90_header();
}

/*
 * End of file
 */
void
ejobcode(int flag)
{
	/* Nothing special needed */
}

/*
 * Called before arg evaluation for a function call
 */
void
inargsetup(void)
{
	/* Handled by C function call syntax */
}

/*
 * Called before function epilogue
 */
void
fixit(void)
{
	/* Nothing needed */
}

/*
 * Initialization code for a function
 */
void
bfunc(struct symtab *sp)
{
	/* Function prologue handled in local2.c */
}

/*
 * Called after function body is compiled
 */
void
efunc(void)
{
	/* Function epilogue handled in local2.c */
}

/*
 * Define a name (variable or function)
 */
void
defnam(struct symtab *sp)
{
	char *name = getexname(sp);
	TWORD t = sp->stype;

	/* Emit C declaration */
	if (ISFTN(t)) {
		/* Function declaration handled separately */
	} else {
		/* Variable declaration */
		if (sp->sclass == EXTDEF)
			printf("extern ");

		/* Type */
		if (ISPTR(t))
			printf("void *");
		else if (t == INT)
			printf("int ");
		else if (t == LONG)
			printf("long ");
		else if (t == SHORT)
			printf("short ");
		else if (t == CHAR)
			printf("char ");
		else if (t == FLOAT)
			printf("float ");
		else if (t == DOUBLE)
			printf("double ");
		else
			printf("int ");

		printf("%s;\n", name);
	}
}

/*
 * Initialize a local variable
 */
void
defzero(struct symtab *sp)
{
	char *name = getexname(sp);
	printf("\t%s = 0;\n", name);
}
