/*
 * Copyright (c) 2025 PCC DEC MACRO Compiler
 *
 * Main entry point for DEC MACRO assembler (mcom)
 * Pass 1: Lexical analysis, parsing, macro expansion, assembly
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "pass1.h"

/* External parser function */
extern int yyparse(void);
extern FILE *yyin;

/* Global variables */
int lineno = 1;
char *ftitle = "<stdin>";

/* Command-line options */
static int verbose = 0;
static int dump_symtab_flag = 0;
static int list_output = 0;

/*
 * Print usage information
 */
static void
usage(void)
{
	fprintf(stderr,
	    "Usage: mcom [options] [file]\n"
	    "DEC MACRO Assembly Language Compiler\n"
	    "\n"
	    "Options:\n"
	    "  -o file       Write output to file\n"
	    "  -l            Generate listing output\n"
	    "  -v            Verbose output\n"
	    "  --dump-symtab Dump symbol table\n"
	    "  -h, --help    Show this help\n"
	    "\n"
	    "Supported DEC architectures:\n"
	    "  - PDP-10 (36-bit)\n"
	    "  - PDP-11 (16-bit)\n"
	    "  - VAX (32-bit)\n"
	    "\n"
	    "Examples:\n"
	    "  mcom prog.mac           # Assemble prog.mac to stdout\n"
	    "  mcom -o prog.s prog.mac # Assemble to prog.s\n"
	    "  mcom -l prog.mac        # Generate listing\n");
	exit(1);
}

/*
 * Parse command-line arguments
 */
static void
parse_args(int argc, char **argv)
{
	int i;

	for (i = 1; i < argc; i++) {
		if (argv[i][0] == '-') {
			/* Option */
			if (strcmp(argv[i], "-o") == 0) {
				/* Output file */
				if (++i >= argc) {
					fprintf(stderr, "error: -o requires argument\n");
					usage();
				}
				outfile = fopen(argv[i], "w");
				if (outfile == NULL) {
					perror(argv[i]);
					exit(1);
				}
			} else if (strcmp(argv[i], "-l") == 0) {
				/* Listing output */
				list_output = 1;
			} else if (strcmp(argv[i], "-v") == 0) {
				/* Verbose */
				verbose = 1;
			} else if (strcmp(argv[i], "--dump-symtab") == 0) {
				/* Dump symbol table */
				dump_symtab_flag = 1;
			} else if (strcmp(argv[i], "-h") == 0 ||
			           strcmp(argv[i], "--help") == 0) {
				usage();
			} else {
				fprintf(stderr, "error: unknown option '%s'\n", argv[i]);
				usage();
			}
		} else {
			/* Input file */
			ftitle = argv[i];
			yyin = fopen(ftitle, "r");
			if (yyin == NULL) {
				perror(ftitle);
				exit(1);
			}
		}
	}

	/* Default output to stdout */
	if (outfile == NULL)
		outfile = stdout;
}

/*
 * Main entry point
 */
int
main(int argc, char **argv)
{
	int ret;

	/* Initialize subsystems */
	error_init();
	symtab_init();
	macro_init();
	codegen_init();

	/* Parse arguments */
	parse_args(argc, argv);

	if (verbose) {
		fprintf(stderr, "PCC DEC MACRO Compiler\n");
		fprintf(stderr, "Input: %s\n", ftitle);
	}

	/* Emit header comment */
	fprintf(outfile, "; Generated by PCC DEC MACRO Compiler\n");
	fprintf(outfile, "; Source: %s\n", ftitle);
	fprintf(outfile, "\n");

	/* Parse input */
	ret = yyparse();

	/* Check for errors */
	if (nerrors > 0) {
		fprintf(stderr, "%d error%s generated.\n",
		    nerrors, nerrors == 1 ? "" : "s");
		return 1;
	}

	if (nwarnings > 0 && verbose) {
		fprintf(stderr, "%d warning%s generated.\n",
		    nwarnings, nwarnings == 1 ? "" : "s");
	}

	/* Dump symbol table if requested */
	if (dump_symtab_flag) {
		dump_symtab();
	}

	if (verbose) {
		fprintf(stderr, "Assembly successful.\n");
	}

	/* Close files */
	if (yyin != stdin)
		fclose(yyin);
	if (outfile != stdout)
		fclose(outfile);

	return ret;
}
