; Generated by PCC DEC MACRO Compiler
; Source: ../tests/hello.mac

	.psect	DATA
	.ascii	"Hello, World!"
L100:
	.byte	0x0d
L101:
	.psect	CODE
	.entry	START
L0:
	MOV	MSG,r0
	MOV	MSGLEN,r1
	MOV	#1,r2
	CLR	r0
	HALT
	.end
