/* Generated by PXC (Xbase++ Compiler) */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <pxc/xbrt.h>


xb_value_t* Main(void)
{
	(nValue == 42);
	return nValue;
}
